[package]
name = "jump"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
chrono = { version = "0.4.40", features = ["alloc"] }
serde = "1"
serde-saphyr = "0.0"

[dev-dependencies]
tempfile = "3"
