[package]
name = "upgrade"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
crossterm = "0.28"
ratatui = "0.29"
shellexpand = "3"
tokio = { version = "1", features = ["full"] }
