# <https://github.com/henriklovhaug/md-tui?tab=readme-ov-file#configuration>

# General settings
emoji_check_marks = false
help_box = false
width = 0
flavor = "claude"

# Keyboard actions
down = ["j", "C-e"]
up = ["k", "C-y"]
page_down = ["d", "space"]
